// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_defeat_friend = "CgkIh4PKnasKEAIQEA"; // <GPGSID>
        public const string achievement_like_a_baby = "CgkIh4PKnasKEAIQFQ"; // <GPGSID>
        public const string achievement_defeat_insane_computer_master = "CgkIh4PKnasKEAIQDw"; // <GPGSID>
        public const string achievement_defeat_computer = "CgkIh4PKnasKEAIQAA"; // <GPGSID>
        public const string achievement_defeat_insane_computer_beginner = "CgkIh4PKnasKEAIQDQ"; // <GPGSID>
        public const string achievement_defeat_difficult_computer_beginner = "CgkIh4PKnasKEAIQCQ"; // <GPGSID>
        public const string achievement_one_punch = "CgkIh4PKnasKEAIQFA"; // <GPGSID>
        public const string achievement_defeat_friend_advanced = "CgkIh4PKnasKEAIQEg"; // <GPGSID>
        public const string achievement_defeat_insane_computer = "CgkIh4PKnasKEAIQDA"; // <GPGSID>
        public const string achievement_defeat_computer_master = "CgkIh4PKnasKEAIQAw"; // <GPGSID>
        public const string achievement_defeat_difficult_computer_master = "CgkIh4PKnasKEAIQCw"; // <GPGSID>
        public const string achievement_defeat_normal_computer_beginner = "CgkIh4PKnasKEAIQBQ"; // <GPGSID>
        public const string achievement_defeat_friend_master = "CgkIh4PKnasKEAIQEw"; // <GPGSID>
        public const string achievement_defeat_normal_computer = "CgkIh4PKnasKEAIQBA"; // <GPGSID>
        public const string achievement_defeat_insane_computer_advanced = "CgkIh4PKnasKEAIQDg"; // <GPGSID>
        public const string achievement_defeat_friend_beginner = "CgkIh4PKnasKEAIQEQ"; // <GPGSID>
        public const string achievement_defeat_computer_advanced = "CgkIh4PKnasKEAIQAg"; // <GPGSID>
        public const string achievement_defeat_computer_beginner = "CgkIh4PKnasKEAIQAQ"; // <GPGSID>
        public const string achievement_defeat_normal_computer_master = "CgkIh4PKnasKEAIQBw"; // <GPGSID>
        public const string achievement_defeat_normal_computer_advanced = "CgkIh4PKnasKEAIQBg"; // <GPGSID>
        public const string achievement_defeat_difficult_computer = "CgkIh4PKnasKEAIQCA"; // <GPGSID>
        public const string achievement_defeat_difficult_computer_advanced = "CgkIh4PKnasKEAIQCg"; // <GPGSID>

}

